[
 {
  "UberDateLog": "31/07/2021 20-35-40",
  "UberLogs": [
   "31/07/2021 20-35-40",
   "Configurations Loaded successfully",
   "Creating folder successfully",
   "Folder Structure created successfully",
   "CSV and HTML files copied successfully to the newly created folders",
   "Date and Time Data successfully loaded in the dataframe",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 57",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "31/07/2021 20-37-03",
  "UberLogs": [
   "31/07/2021 20-37-03",
   "Configurations Loaded successfully",
   "Creating folder successfully",
   "Folder Structure created successfully",
   "CSV and HTML files copied successfully to the newly created folders",
   "Date and Time Data successfully loaded in the dataframe",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 57",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "01/08/2021 17-47-30",
  "UberLogs": [
   "01/08/2021 17-47-30",
   null
  ]
 },
 {
  "UberDateLog": "01/08/2021 17-49-00",
  "UberLogs": [
   "01/08/2021 17-49-00",
   "None"
  ]
 },
 {
  "UberDateLog": "01/08/2021 18-46-36",
  "UberLogs": [
   "01/08/2021 18-46-36",
   "Cannot load the folder settings from folder_config.json, Exiting the Program!!!",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 39, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n"
  ]
 },
 {
  "UberDateLog": "01/08/2021 18-56-03",
  "UberLogs": [
   "01/08/2021 18-56-03",
   "ERROR: Cannot load the folder settings from folder_config.json, Exiting the Program!!!",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 52, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n"
  ]
 },
 {
  "UberDateLog": "01/08/2021 18-58-31",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json, Exiting the Program!!!",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 53, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n"
  ]
 },
 {
  "UberDateLog": "01/08/2021 18-59-12",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json, Exiting the Program!!!",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 54, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n"
  ]
 },
 {
  "UberDateLog": "01/08/2021 19-01-05",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json, Exiting the Program!!!",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 54, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 19-13-59 AM/PM",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json!!!",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 53, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 07-15 PM",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json!!!",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 53, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 07-16-25 PM",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json!!!",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 53, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 08-37-21 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "ERROR: Required HTML and CSV file(s) cannot be copied in designated folders.",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 181, in <module>\n    copy_files_to_dest_folder(HTMLTemplatefiles_src, HTMLDirName)\nNameError: name 'HTMLDirName' is not defined\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 08-41-20 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 207, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\core\\reshape\\concat.py\", line 274, in concat\n    op = _Concatenator(\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\core\\reshape\\concat.py\", line 331, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 08-43-41 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 208, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\core\\reshape\\concat.py\", line 274, in concat\n    op = _Concatenator(\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\core\\reshape\\concat.py\", line 331, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 08-48-18 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"d:\\UberBuild\\UberCleaningRecordBuilder.py\", line 209, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\core\\reshape\\concat.py\", line 274, in concat\n    op = _Concatenator(\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\core\\reshape\\concat.py\", line 331, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 08-53-23 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 114",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "01/08/2021 09-44-03 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 09-47-45 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 09-53-31 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 09-56-30 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 10-12-05 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 10-26-28 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 10-47-59 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 10-58-17 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 11-07-53 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "01/08/2021 11-12-39 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/UberCleaningRecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-18-33 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 207, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-25-32 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 207, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-29-09 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 207, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-31-43 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 207, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-37-44 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 209, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-38-59 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "ERROR: File(s) cannot be copied in required folders.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 163, in copy_files_to_dest_folder\n    copyfile(src_files, dest_files)\n  File \"/home/manny/anaconda3/lib/python3.7/shutil.py\", line 121, in copyfile\n    with open(dst, 'wb') as fdst:\nPermissionError: [Errno 13] Permission denied: '/home/manny/UberCleaningRecord/Temp/HTML/UberCleaningRecordFooterTemplate.html'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-38-59 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "ERROR: File(s) cannot be copied in required folders.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 163, in copy_files_to_dest_folder\n    copyfile(src_files, dest_files)\n  File \"/home/manny/anaconda3/lib/python3.7/shutil.py\", line 121, in copyfile\n    with open(dst, 'wb') as fdst:\nPermissionError: [Errno 13] Permission denied: '/home/manny/UberCleaningRecord/Temp/HTML/UberCleaningRecordFooterTemplate.html'\n",
   "Exiting the Program",
   "ERROR: Required HTML and CSV file(s) cannot be copied in designated folders.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 163, in copy_files_to_dest_folder\n    copyfile(src_files, dest_files)\n  File \"/home/manny/anaconda3/lib/python3.7/shutil.py\", line 121, in copyfile\n    with open(dst, 'wb') as fdst:\nPermissionError: [Errno 13] Permission denied: '/home/manny/UberCleaningRecord/Temp/HTML/UberCleaningRecordFooterTemplate.html'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 183, in <module>\n    copy_files_to_dest_folder(HTMLTemplatefiles_src, HTMLDirName)\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 168, in copy_files_to_dest_folder\n    UberLogException(\"ERROR: File(s) cannot be copied in required folders.\", True, True)\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 36, in UberLogException\n    if UberSystemExit == True: sys.exit()\nSystemExit\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-46-02 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 57",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-48-49 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "ERROR: Folder structure cannot be created.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 127, in <module>\n    os.makedirs(dirName)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 211, in makedirs\n    makedirs(head, exist_ok=exist_ok)\n  File \"/home/manny/anaconda3/lib/python3.7/os.py\", line 221, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/cleaningrecord'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-49-38 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 209, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-51-45 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 209, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-54-49 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "ERROR: Date and Time Data cannot be loaded in the dataframe.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 209, in <module>\n    UberTripData = pd.concat(TempUberTripDataList, axis=0, ignore_index=True)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 304, in concat\n    sort=sort,\n  File \"/home/manny/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 351, in __init__\n    raise ValueError(\"No objects to concatenate\")\nValueError: No objects to concatenate\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 12-55-56 AM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 57",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "02/08/2021 01-54-22 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 2",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "02/08/2021 02-21-22 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "Sending Records to UberCleaningRecords table through InsertJSONCleaningRecord stored procedure",
   "Insert succeeded to UberCleaningRecords, row count = 2",
   "Records successfully sent to UberCleaningRecords in database !!!",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "02/08/2021 08-14-47 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "ERROR: Cleaning Records could not be sent to UberTempCleaningRecords.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 279, in <module>\n    time.sleep(0.5)  # emulating long-playing job\nAttributeError: type object 'datetime.time' has no attribute 'sleep'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "02/08/2021 08-14-47 PM",
  "UberLogs": [
   "Folder settings from folder_config.json Loaded successfully.",
   "Config settings from config.json Loaded successfully.",
   "Database credentials from DBconfig.json Loaded successfully.",
   "DataFrame configurations from DataFrameConfig.json Loaded successfully.",
   "All required configurations Loaded successfully.",
   "Folder Structure created successfully.",
   "CSV and HTML files copied successfully to the newly created designated folders.",
   "Date and Time Data successfully loaded in the dataframe.",
   "Creating the final dataframe having all the required columns",
   "Connecting to Database",
   "Sending Records to UberTempCleaningRecords table in database....",
   "ERROR: Cleaning Records could not be sent to UberTempCleaningRecords.",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 279, in <module>\n    time.sleep(0.5)  # emulating long-playing job\nAttributeError: type object 'datetime.time' has no attribute 'sleep'\n",
   "Exiting the Program",
   "Renaming the dataframe columns to one provided in the CPVV Template !!!",
   "Rendering the dataframe to HTML!!!",
   "Concatenating the final HTML!!!",
   "Saving the final HTML to HTML file in HTML Folder!!!",
   "Begin to write the PDF file from the resultant HTML!!!",
   "PDF written successfully from the resultant HTML file!!!"
  ]
 },
 {
  "UberDateLog": "03/08/2021 03-53-41 PM",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json!!!",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 56, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 },
 {
  "UberDateLog": "03/08/2021 05-07-17 PM",
  "UberLogs": [
   "ERROR: Cannot load the folder settings from folder_config.json!!!",
   "Traceback (most recent call last):\n  File \"/home/manny/UberBuild/UberCleaningRecordBuilder.py\", line 23, in <module>\n    FolderConfigJSON = open('./Config/folder_config.json')\nFileNotFoundError: [Errno 2] No such file or directory: './Config/folder_config.json'\n",
   "Exiting the Program"
  ]
 }
]